# Exact published PCI IDs admit read-only identification, never native engines.
param([Parameter(Mandatory)][string]$SourceReadme)
$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
$source=[IO.Path]::GetFullPath($SourceReadme)
$hash='8fcec472d54b8f4839e26b5ecd025cfc4ed6388a77877bddc97d686fc10670bc'
if((Get-FileHash -LiteralPath $source).Hash.ToLowerInvariant() -cne $hash){throw 'Expected the unmodified NVIDIA570.144 README'}
$text=[IO.File]::ReadAllText($source)
$published=@([regex]::Matches($text,'(?m)^\|[^\r\n|]+\|\s*([0-9A-Fa-f]{4})\s*\|')|
    ForEach-Object {[Convert]::ToUInt16($_.Groups[1].Value,16)}|Sort-Object -Unique)
$groups=@(
    @{name='ampere';count=70;select={($_ -ge 0x2200 -and $_ -lt 0x2300) -or ($_ -ge 0x2400 -and $_ -lt 0x2600)}},
    @{name='turing';count=65;select={$_ -ge 0x1e00 -and $_ -lt 0x2000}},
    @{name='ada';count=39;select={$_ -ge 0x2600 -and $_ -lt 0x2900}},
    @{name='blackwell';count=11;select={$_ -ge 0x2b00 -and $_ -lt 0x3000}})
$table="// Published NVIDIA570.144 README PCI IDs: read-only identification, not capability.`n// Source commit: 8ec351aeb96a93a4bb69ccc12a542bf8a8df2b6f.`n// README SHA256: $hash`n// Generated by Tools/GenerateProbeIds.ps1.`n"
foreach($group in $groups){
 $ids=@($published|Where-Object $group.select)
 if($ids.Count -ne $group.count){throw "Unexpected probe group $($group.name)"}
 $table+='pub const '+$group.name+" = [_]u16{`n"
 for($i=0;$i -lt $ids.Count;$i+=8){$table+='    '+(($ids[$i..([Math]::Min($ids.Count-1,$i+7))]|ForEach-Object {'0x{0:x4}' -f $_}) -join ', ')+",`n"}
 $table+="};`n"
}
$table+="pub const all = ampere ++ turing ++ ada ++ blackwell;`n"
[IO.File]::WriteAllText((Join-Path (Split-Path -Parent $PSScriptRoot) 'src/probe_ids.zig'),$table,[Text.UTF8Encoding]::new($false))
Write-Output 'NVIDIA570.144: 185 exact read-only probe IDs generated.'
